#!/bin/bash

set -e
command=$1

print_help() {
  echo "Available commands:"
  echo ""
  echo -e "\033[1;33mls\033[0m    - lists all available themes"
  echo -e "\033[1;33mset\033[0m   - applies a theme"
}

print_list() {
  echo ""
  echo -e "Available prompt themes:\033[0;34m"
  ls $HOME/.py-prompts/themes | rev | cut -d "." -f 2- | rev | tr '\n' ','
  echo -e "\033[0m"
}

if [ -z $command ]; then
  print_help
  exit 1
fi

if [ "$command" = "help" ]; then
  print_help
  exit 0
fi

if [ "$command" = "ls" ]; then
  print_list
  exit 0
fi

if [ "$command" = "set" ]; then
  theme_name=$2
  if [ -z "$theme_name" ]; then
    echo -e "\033[1;33musage: py-prompts set <theme_name>\033[0m"
    print_list
  else
    echo -e "Setting theme \033[1;33m$theme_name\033[0m"
    if [ ! -f "$HOME/.py-prompts/themes/$theme_name.py" ]; then
      echo -e "\033[0;31mtheme $theme_name does not exist.\033[0m"
      print_list
      exit 1
    fi
    if [ -f $HOME/.bashrc ]; then
      echo "export PYTHONSTARTUP=$HOME/.py-prompts/themes/$theme_name.py" >> $HOME/.bashrc
    elif [ -f $HOME/.zshrc ]; then
      echo "export PYTHONSTARTUP=$HOME/.py-prompts/themes/$theme_name.py" >> $HOME/.zshrc
    else
      echo -e "\033[0;31mCould not detect your rc file. kindly add the following line in your rc file.\033[0m"
      echo -e "\033[0;34mexport PYTHONSTARTUP=$HOME/.py-prompts/themes/$theme_name.py\033[0m"
    fi
  fi
  exit 0
fi

print_help
exit 1
